# Generated by Django 4.1.1 on 2022-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0002_accountexpenses_netprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountexpenses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
