# Generated by Django 4.1.1 on 2022-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0007_labourexpenses_gettime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountexpenses',
            name='PaperPresentToday',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='PaperSoldToday',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='PaperYesterday',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
