# Generated by Django 4.1.1 on 2022-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0009_accountexpenses_pastsolddetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bata1', models.IntegerField(default=90)),
                ('bata2', models.IntegerField(default=70)),
                ('food', models.IntegerField(default=150)),
                ('tajSalary', models.DecimalField(decimal_places=2, default=633.33, max_digits=9)),
                ('noorSalary', models.DecimalField(decimal_places=2, default=466.66, max_digits=9)),
                ('assanSalary', models.DecimalField(decimal_places=2, default=466.66, max_digits=9)),
                ('maniSalary', models.DecimalField(decimal_places=2, default=333.33, max_digits=9)),
                ('rasheedSalary', models.DecimalField(decimal_places=2, default=333.33, max_digits=9)),
                ('tpmRent', models.DecimalField(decimal_places=2, default=516.66, max_digits=9)),
                ('kdmRent', models.DecimalField(decimal_places=2, default=800.0, max_digits=9)),
                ('currentBillKdm', models.IntegerField(default=110)),
                ('currentBillTpm', models.IntegerField(default=110)),
            ],
        ),
    ]
