# Generated by Django 4.1.1 on 2022-09-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0013_accountexpenses_toner'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='TonerSpent',
            field=models.IntegerField(default=0),
        ),
    ]
