# Generated by Django 4.1.1 on 2022-09-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0015_alter_labourexpenses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='ColourMachineReading2',
            field=models.IntegerField(default=0),
        ),
    ]
