# Generated by Django 4.1.1 on 2022-09-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0017_ratesheet_b2brate_ratesheet_paperrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratesheet',
            name='copiesPerToner',
            field=models.IntegerField(default=19000),
        ),
    ]
