# Generated by Django 4.1.1 on 2022-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='NetProfit',
            field=models.IntegerField(default=1),
        ),
    ]
