# Generated by Django 4.1.1 on 2022-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0005_rename_stayingcopies_accountexpenses_todaystayingcopies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='GetTime',
            field=models.IntegerField(default=1),
        ),
    ]
