# Generated by Django 4.1.1 on 2022-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0006_accountexpenses_gettime'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourexpenses',
            name='GetTime',
            field=models.IntegerField(default=1),
        ),
    ]
