# Generated by Django 4.1.1 on 2022-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0008_alter_accountexpenses_paperpresenttoday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='PastSoldDetail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='PastStayDetail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='TodayStayDetail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
