# Generated by Django 4.1.1 on 2022-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0009_accountexpenses_pastsolddetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountexpenses',
            name='PaperYesterday',
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='ItemsInfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='isItemsCame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='isPaperCame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='isTonerCame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='Day',
            field=models.CharField(default='MON', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='PaperPresentToday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='PaperSoldToday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='isHoliday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountexpenses',
            name='isSunday',
            field=models.IntegerField(default=0),
        ),
    ]
