# Generated by Django 4.1.1 on 2022-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0010_remove_accountexpenses_paperyesterday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='PaperSheet',
            field=models.IntegerField(default=0),
        ),
    ]
