# Generated by Django 4.1.1 on 2022-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0013_accountexpenses_tonerspent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourexpenses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
