# Generated by Django 4.1.1 on 2022-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0015_accountexpenses_paperquantitycame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourexpenses',
            name='isAssanHalfDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labourexpenses',
            name='isManiHalfDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labourexpenses',
            name='isRasheedHalfDay',
            field=models.IntegerField(default=0),
        ),
    ]
